# Generated by Django 6.0.8 on 2026-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('reviewed', 'Consultée par le recruteur'), ('shortlisted', 'Présélectionnée'), ('interview', 'Entretien planifié'), ('rejected', 'Non retenue'), ('hired', 'Recrutée')], default='submitted', max_length=20)),
                ('match_score', models.PositiveSmallIntegerField(default=0, help_text='Score de compatibilité (0-100)')),
                ('match_explanation', models.JSONField(blank=True, default=dict, help_text='Détail structuré : compétences présentes/manquantes, conseils')),
                ('fraud_flag', models.BooleanField(default=False, help_text='Incohérence détectée à vérifier manuellement')),
                ('fraud_reason', models.CharField(blank=True, max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-match_score', '-applied_at'],
            },
        ),
    ]
