# Generated by Django 6.0.8 on 2026-08-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, verbose_name='Missions')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance / Prestation'), ('alternance', 'Alternance')], default='cdi', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Lieu')),
                ('remote_type', models.CharField(choices=[('presentiel', 'Présentiel'), ('hybride', 'Hybride'), ('teletravail', 'Télétravail complet')], default='presentiel', max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='FCFA/mois', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='FCFA/mois', null=True)),
                ('experience_years_required', models.PositiveSmallIntegerField(default=0)),
                ('education_level_required', models.CharField(blank=True, choices=[('', 'Non requis'), ('bac', 'Baccalauréat'), ('bac2', 'Bac+2 (BTS/DUT)'), ('licence', 'Licence / Bac+3'), ('master', 'Master / Bac+5'), ('doctorat', 'Doctorat')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('closed', 'Clôturée')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to='companies.recruiter')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='jobs.joboffer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_in_jobs', to='candidates.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='joboffer',
            name='skills',
            field=models.ManyToManyField(related_name='job_offers', through='jobs.JobRequiredSkill', to='candidates.skill'),
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='jobs.joboffer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['status', 'created_at'], name='jobs_joboff_status_2c5e6d_idx'),
        ),
    ]
