# Generated by Django 6.0.8 on 2026-08-05 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv_extraction', 'Extraction de CV'), ('cv_generation', 'Génération de CV'), ('cover_letter', 'Lettre de motivation'), ('matching', 'Explication de matching'), ('interview_questions', "Questions d'entretien"), ('interview_feedback', 'Analyse de réponse'), ('learning_plan', 'Plan de progression'), ('fraud_check', 'Vérification de cohérence')], max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='ai_engine_a_kind_521111_idx')],
            },
        ),
    ]
