# Generated by Django 6.0.8 on 2026-08-05 09:40

import candidates.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('position_title', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150, verbose_name='Diplôme')),
                ('institution', models.CharField(max_length=150, verbose_name='Établissement')),
                ('field_of_study', models.CharField(blank=True, max_length=150, verbose_name="Domaine d'étude")),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Poste')),
                ('company', models.CharField(max_length=150, verbose_name='Entreprise')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('professionnel', 'Professionnel'), ('moderne', 'Moderne'), ('minimaliste', 'Minimaliste'), ('creatif', 'Créatif')], default='professionnel', max_length=20)),
                ('content_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('secondaire', 'Secondaire'), ('bac', 'Baccalauréat'), ('bac2', 'Bac+2 (BTS/DUT)'), ('licence', 'Licence / Bac+3'), ('master', 'Master / Bac+5'), ('doctorat', 'Doctorat')], max_length=20)),
                ('headline', models.CharField(blank=True, help_text='Ex: Développeur Backend Django', max_length=150)),
                ('bio', models.TextField(blank=True, verbose_name='À propos')),
                ('desired_salary', models.PositiveIntegerField(blank=True, help_text='Salaire mensuel souhaité (FCFA)', null=True)),
                ('availability', models.CharField(choices=[('immediate', 'Disponible immédiatement'), ('1_mois', 'Sous 1 mois'), ('3_mois', 'Sous 3 mois'), ('negociable', 'À négocier')], default='negociable', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.models.photo_upload_path)),
                ('cv_file', models.FileField(blank=True, help_text='CV importé (PDF ou DOCX, 5 Mo max)', null=True, upload_to=candidates.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('cv_imported_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completeness', models.PositiveSmallIntegerField(default=0, help_text='Score de complétude du profil (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil candidat',
                'verbose_name_plural': 'Profils candidats',
            },
        ),
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Intermédiaire avancé'), ('C1', 'C1 - Avancé'), ('C2', 'C2 - Bilingue / natif')], default='B1', max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_languages', to='candidates.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='intermediaire', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='candidates.candidateprofile')),
            ],
        ),
    ]
