# Generated by Django 6.0.8 on 2026-08-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='jobs.joboffer'),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='generatedcv',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cvs', to='candidates.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.language'),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='candidates.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatelanguage',
            unique_together={('profile', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together={('profile', 'skill')},
        ),
    ]
