# Generated by Django 6.0.8 on 2026-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='theme',
            field=models.CharField(default='cote_ivoire', max_length=30),
        ),
        migrations.AlterField(
            model_name='generatedcv',
            name='style',
            field=models.CharField(choices=[('professionnel', 'Professionnel'), ('moderne', 'Moderne'), ('minimaliste', 'Minimaliste'), ('creatif', 'Créatif')], default='moderne', max_length=20),
        ),
    ]
