# Generated by Django 6.0.8 on 2026-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_generatedcv_theme_alter_generatedcv_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcv',
            name='style',
            field=models.CharField(default='moderne', max_length=30),
        ),
    ]
