# Generated by Django 6.0.8 on 2026-08-05 09:40

import companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Raison sociale')),
                ('sector', models.CharField(blank=True, max_length=150, verbose_name="Secteur d'activité")),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=companies.models.logo_upload_path)),
                ('website', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, choices=[('tpe', '1-9 salariés (TPE)'), ('pme', '10-249 salariés (PME)'), ('eti', '250-4999 salariés (ETI)'), ('ge', '5000+ salariés (Grande entreprise)')], max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='Vérifiée par un administrateur de la plateforme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('is_company_admin', models.BooleanField(default=False, help_text="Peut gérer les autres recruteurs de l'entreprise")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruteur',
                'verbose_name_plural': 'Recruteurs',
            },
        ),
    ]
